version: '3.8'

services:

  nginx:
    working_dir: /app
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
      - postgresql  
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf 
    networks:
      - internal 
      
  php: 
    build:
      context: .
    container_name: 'php'
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/supervisor/supervisor.conf:/etc/supervisor.conf 
      - ./docker/supervisor/conf.d:/etc/supervisor/
    labels:
      chadburn.enabled: "true"
      chadburn.job-exec.datecron.schedule: "@every 60s"
      chadburn.job-exec.datecron.command: "su - www-data -c 'php artisan schedule:run >> /dev/null 2>&1'"
    
    networks:
      - internal  

  postgresql:
    
    ports:
      - '${PGSQL_PORT}:5432'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: '${PGSQL_DB}'
      POSTGRES_USER: '${PGSQL_USER}'
      POSTGRES_PASSWORD: '${PGSQL_PASSWORD}'
    volumes:
      - ./docker/data/dump/:/app/dump/
      - ./docker/data/postgresql:/docker-entrypoint-initdb.d/
    
    networks:
      - internal 

  rabbitmq:
    working_dir: /app
    hostname: rabbit
    ports:
      - '${RABBIT_PORT}:5672'
      - '${RABBIT_ADMIN_PORT}:15672'
      
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBIT_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBIT_PASSWORD}'
      RABBITMQ_DEFAULT_VHOST: '${RABBIT_HOST}'
    
    networks:
      - internal
    
  redis:
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis:/var/lib/redis
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    environment:
      REDIS_PORT: '6379'  
      
    networks:
      - internal
  app:
    ports:
      - $JS_NGINX_LOCAL_PORT:$JS_NGINX_DOCKER_PORT
    restart: no    
    stdin_open: true
    tty: true
    networks:
      - internal
    
  centrifugo:  
    volumes:
      - ./docker/centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - internal      
          
  chadburn:
    depends_on:
      - php
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  
    networks:
      - internal  
        

volumes:
  postgresql:
     driver: local
  
  redis:
     driver: local  
  
networks:
  internal:
    driver: bridge
